version: '3.3'

services:
  ncplot:
    image: epinux/metsis-fastapi
    environment:
        DOWNLOAD_DIR: "/app/static/download"
    volumes:
        - ./app:/app
    ports:
      - 7000:80
    networks:
      - net
      - traefik-public
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2048M
        reservations:
          cpus: '0.25'
          memory: 512M
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.adcplot-http.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.adcplot-http.entrypoints=http
        - traefik.http.routers.adcplot-http.middlewares=https-redirect
        - traefik.http.routers.adcplot-https.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.adcplot-https.entrypoints=https
        - traefik.http.routers.adcplot-https.tls=true
        - traefik.http.routers.adcplot-https.tls.certresolver=le
        - traefik.http.services.adcplot.loadbalancer.server.port=80
        # allow CORS
        - "traefik.http.middlewares.testheader.headers.accesscontrolallowmethods=GET,OPTIONS,PUT"
        - "traefik.http.middlewares.testheader.headers.accesscontrolalloworiginlist=*"
        - "traefik.http.middlewares.testheader.headers.accesscontrolmaxage=100"
        - "traefik.http.middlewares.testheader.headers.addvaryheader=true"

  hyrax:
    image: epinux/metsis-hyrax
    volumes:
      - ./data:/usr/share/hyrax
    networks:
      - net
    ports:
      - "9090:8080"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2048M
        reservations:
          cpus: '0.25'
          memory: 512M


networks:
  net:
    driver: overlay
    attachable: true
  traefik-public:
    external: true
